from setuptools import setup

version = "4.5.2.dev0"

setup(
    name="collective.easyform",
    version=version,
    description="Forms for Plone",
    long_description=open("README.rst").read() + "\n" + open("CHANGES.rst").read(),
    # Get more strings from https://pypi.org/classifiers/
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Environment :: Web Environment",
        "Framework :: Plone",
        "Framework :: Plone :: Addon",
        "Framework :: Plone :: 6.2",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Programming Language :: Python :: 3.14",
        "Operating System :: OS Independent",
        "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    ],
    keywords="form plone ttw builder email",
    author="Roman Kozlovskyi",
    author_email="krzroman@gmail.com",
    maintainer="Plone Release Team",
    maintainer_email="releaseteam@plone.org",
    url="https://github.com/collective/collective.easyform",
    license="GPLv2",
    include_package_data=True,
    zip_safe=False,
    python_requires=">=3.10",
    install_requires=[
        "AccessControl",
        "beautifulsoup4",
        "lxml",
        "openpyxl",
        "plone.api",
        "plone.autoform",
        "plone.app.contenttypes",
        "plone.app.dexterity",
        "plone.app.registry",
        "plone.app.textfield",
        "plone.app.z3cform",
        "plone.base",
        "plone.dexterity",
        "plone.memoize",
        "plone.namedfile",
        "plone.protect",
        "plone.resourceeditor",
        "plone.restapi",
        "plone.registry",
        "plone.schema",
        "plone.schemaeditor",
        "plone.supermodel",
        "Products.CMFCore",
        "Products.CMFPlone",
        "Products.statusmessages",
        "Products.validation",
        "python-dateutil",
        "z3c.form",
        "Zope",
    ],
    extras_require={
        "test": [
            "collective.z3cform.norobots",
            "Products.MailHost",
            "plone.app.testing[robot]",
            "plone.app.robotframework",
            "plone.app.contenttypes",
            "plone.formwidget.recaptcha",
            "plone.formwidget.hcaptcha",
            "plone.testing",
            "robotsuite",
            "Zope",
            "transaction",
        ],
        "downloadxlsx": ["openpyxl"],
        "recaptcha": ["plone.formwidget.recaptcha"],
        "hcaptcha": ["plone.formwidget.hcaptcha"],
        "norobots": ["collective.z3cform.norobots"],
    },
    entry_points="""
    # -*- Entry points: -*-
    [plone.autoinclude.plugin]
    target = plone
    """,
)
